### PR TITLE
Add note to PKCE doc for those who overrode the view

### PR DESCRIPTION
**Pull request by dee-see**
I had issues enabling PKCE today and found this [StackOverflow post](https://stackoverflow.com/questions/59379154/enable-pkce-with-doorkeeper) that saved me. I felt like it was worth adding a note to the documentation.

### CODE REVIEW

**Review by nbulaj — APPROVED** [review]

**Comment by nbulaj** [comment]
Thanks @dee-see !

**Comment by dee-see** [comment]
Thanks for the quick merge! Should I also update https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-PKCE-flow or it will be synchronized automatically somehow?

**Comment by nbulaj** [comment]
Will be great if you also update it, yes, 
Unfortunately we don't have automated updates for the Wiki

**Comment by dee-see** [comment]
Done, and I opened https://github.com/doorkeeper-gem/guides/pull/9 because some info existed only in the wiki

**Pull request merged**
