### PR TITLE
Change documentation to match secret storing PR

### PR DESCRIPTION
**Pull request by oliverguenther**
Relevant PR: https://github.com/doorkeeper-gem/doorkeeper/pull/1208

### CODE REVIEW

**Comment by nbulaj** [comment]
Seems like it must be updated to latest version, @oliverguenther

**Comment by felipeelias** [comment]
@oliverguenther @nbulaj any updates?

**Comment by oliverguenther** [comment]
Hi guys, I don't quite see the changes necessary. Documentation here still seems to be korrekt wrt the linked PR. What did you mean?

**Comment by nbulaj** [comment]
We have some refactoring do I thought it introduced some new changes or break something we already have. If this docs are still up-to-date - I'm OK with it :)

**Comment by oliverguenther** [comment]
The changes I made in the PR were only internal and relevant for new `SecretStrategy` developers such as the encryption PR. This PR only documents end-user usage of the hashing so I believe we're still good!

**Comment by nbulaj** [comment]
Thanks @oliverguenther , good to know!

**Pull request merged**
